name: Libnut Core Create tagged release
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./libnut-core

jobs:
  deploy:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 18 ]
    runs-on: ${{matrix.os}}
    permissions:
      packages: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.1
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure Linux environment
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: sudo apt-get install -y cmake libx11-dev zlib1g-dev libpng-dev libxtst-dev build-essential
      - name: Install
        run: npm run patch && npm i
      - name: Publish tagged release to GitHub Package Registry
        run: |
          ./.build/pre-publish.sh
          npm run publish:next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
