name: node-mac-permissions Create tagged release
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./node-mac-permissions

jobs:
  deploy:
    runs-on: macos-latest
    permissions:
      packages: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm install
      - name: Publish tagged release to GitHub Package Registry
        run: |
          ./.build/pre-publish.sh
          npm run publish:next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
