name: node-mac-permissions Create tagged release
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./node-mac-permissions

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install
      - name: Publish tagged release to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
          npm run publish:next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
