name: Create snapshot release
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          registry-url: 'https://registry.npmjs.org'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - name: Install
        run: pnpm i
      - name: Install @kumar-sambhav/libnut@next
        run: |
          pnpm --filter @kumar-sambhav/libnut i @kumar-sambhav/libnut-darwin@next @kumar-sambhav/libnut-linux@next @kumar-sambhav/libnut-win32@next
      - name: Compile
        run: pnpm run compile
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: pnpm run coverage

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - name: Install
        run: pnpm i
      - name: Install @kumar-sambhav/libnut@next
        run: |
          pnpm --filter @kumar-sambhav/libnut i @kumar-sambhav/libnut-darwin@next @kumar-sambhav/libnut-linux@next @kumar-sambhav/libnut-win32@next
      - name: Create snapshot release
        run: bash ./.build/pre-release.sh
      - name: Publish snapshot release to npm
        run: pnpm run publish:next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
