name: Create tagged release
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 18 ]
    runs-on: ${{matrix.os}}
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      npm_config_strict_ssl: "false"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          registry-url: 'https://npm.pkg.github.com'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - name: Configure registry for @orionstario scope
        run: |
          printf "@orionstario:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=%s\n" "${NODE_AUTH_TOKEN}" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: pnpm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_strict_ssl: "false"
      - name: Compile
        run: npm run compile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      npm_config_strict_ssl: "false"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - name: Configure registry for @orionstario scope
        run: |
          printf "@orionstario:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=%s\n" "${NODE_AUTH_TOKEN}" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: pnpm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_strict_ssl: "false"
      - name: Publish tagged release to GitHub Package Registry
        run: |
          ./.build/pre-publish.sh
          pnpm run publish:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
          npm_config_strict_ssl: "false"
